USE meeting;

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS meeting_events;
DROP TABLE IF EXISTS meeting_participants;
DROP TABLE IF EXISTS meetings;
DROP TABLE IF EXISTS user_sessions;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS=1;
